#!/bin/python3

import math
import os
import random
import re
import sys
import string

#
# Complete the 'caesarCipher' function below.
#
# The function is expected to return a STRING.
# The function accepts following parameters:
#  1. STRING s
#  2. INTEGER k
#

# ========== my code ==========

def caesarCipher(s, k):
    # Write your code here
    alpha = string.ascii_lowercase
    new_alpha = alpha[k % 26:] + alpha[:k % 26]
    
    new_string = ''
    
    for letter in s:
        if letter.isalpha():
            if letter.isupper():
                new_string += new_alpha[alpha.find(letter.lower())].upper()
            else:
                new_string += new_alpha[alpha.find(letter)]
        else:
            new_string += letter
            
    return new_string

# ==============================    
    
if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input().strip())

    s = input()

    k = int(input().strip())

    result = caesarCipher(s, k)

    fptr.write(result + '\n')

    fptr.close()
