#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'diagonalDifference' function below.
#
# The function is expected to return an INTEGER.
# The function accepts 2D_INTEGER_ARRAY arr as parameter.
#

# ========== my code ==========

def diagonalDifference(arr):
    # Write your code here
    diagonal_1 = []
    diagonal_2 = []
    n = len(arr)
    control = 0
    
    
    for i in arr:
        diagonal_1.append(i[control - n])
        diagonal_2.append(i[n - control - 1])
        control += 1
    
    print(diagonal_1)
    print(diagonal_2)

    return abs(sum(diagonal_1) - sum(diagonal_2))
        
# =============================        

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input().strip())

    arr = []

    for _ in range(n):
        arr.append(list(map(int, input().rstrip().split())))

    result = diagonalDifference(arr)

    fptr.write(str(result) + '\n')

    fptr.close()
