#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'flippingMatrix' function below.
#
# The function is expected to return an INTEGER.
# The function accepts 2D_INTEGER_ARRAY matrix as parameter.
#

# ========== my code ==========

def flippingMatrix(matrix):
    # Write your code here
    n = len(matrix) // 2
    total_sum = 0
    
    for row in range(n):
        for column in range(n):
            total_sum += max(
                matrix[row][column],
                matrix[row][2 * n - 1 - column],
                matrix[2 * n - 1 - row][column],
                matrix[2 * n - 1 - row][2 * n - 1 - column]
            )
    
    return total_sum
            
# =============================            

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    q = int(input().strip())

    for q_itr in range(q):
        n = int(input().strip())

        matrix = []

        for _ in range(2 * n):
            matrix.append(list(map(int, input().rstrip().split())))

        result = flippingMatrix(matrix)

        fptr.write(str(result) + '\n')

    fptr.close()
