#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'lonelyinteger' function below.
#
# The function is expected to return an INTEGER.
# The function accepts INTEGER_ARRAY a as parameter.
#

# ========== my code ==========

def lonelyinteger(a):
    # Write your code here
    temp_list = []
    for i in a:
        if i not in temp_list:
            temp_list.append(i)
        elif i in temp_list:
            temp_list.remove(i)
    
    return temp_list[0]

# =============================
    
if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input().strip())

    a = list(map(int, input().rstrip().split()))

    result = lonelyinteger(a)

    fptr.write(str(result) + '\n')

    fptr.close()
