#!/bin/python3

import math
import os
import random
import re
import sys



#
# Complete the 'palindromeIndex' function below.
#
# The function is expected to return an INTEGER.
# The function accepts STRING s as parameter.
#

# ========== my code =========

def palindromeIndex(s):
    # Write your code here
    
    if s == s[::-1]:
        return -1

    for i, item in enumerate(s):
        new_s = s[:i] + s[i + 1:]
        if new_s == new_s[::-1]:
            return i

    return -1

# =============================

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    q = int(input().strip())

    for q_itr in range(q):
        s = input()

        result = palindromeIndex(s)

        fptr.write(str(result) + '\n')

    fptr.close()
