#!/bin/python3

import math
import os
import random
import re
import sys



#
# Complete the 'palindromeIndex' function below.
#
# The function is expected to return an INTEGER.
# The function accepts STRING s as parameter.
#

# ========== my code ===========

def palindromeIndex(s):
    # Write your code here
    
    if s == s[::-1]:
        return -1

    i = 0
    j = len(s) - 1
    
    while i <= len(s) // 2 <= j:
        if s[i] == s[j]:
            i += 1
            j -= 1
            continue
        else:
            a = s[:i] + s[i + 1:]
            b = s[:j] + s[j + 1:]
            
            if a == a[::-1]:
                return i
            elif b == b[::-1]:
                return j
            else:
                i += 1
                j -= 1

# =============================
                
if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    q = int(input().strip())

    for q_itr in range(q):
        s = input()

        result = palindromeIndex(s)

        fptr.write(str(result) + '\n')

    fptr.close()
