#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'plusMinus' function below.
#
# The function accepts INTEGER_ARRAY arr as parameter.
#

# =========== my code ==========

def plusMinus(arr):
    # Write your code here
    n = len(arr)
    pos = 0
    zer = 0
    neg = 0
        
    for i in arr:
        if i > 0:
            pos += 1
        elif i < 0:
            neg += 1
        else:
            zer += 1
    
    print(f'{pos/n:.6f}')
    print(f'{neg/n:.6f}')
    print(f'{zer/n:.6f}')
        
# ==============================

if __name__ == '__main__':
    n = int(input().strip())

    arr = list(map(int, input().rstrip().split()))

    plusMinus(arr)
