#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'superDigit' function below.
#
# The function is expected to return an INTEGER.
# The function accepts following parameters:
#  1. STRING n
#  2. INTEGER k
#

# ========== my code ==========

def superDigit(n, k):
    # Write your code here
    n = str(sum(list(map(lambda x: int(x), n)))) * k
        
    while len(n) > 1:
        n = str(sum(list(map(lambda x: int(x), n))))
    
    return n

# # =============================
    
if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    first_multiple_input = input().rstrip().split()

    n = first_multiple_input[0]

    k = int(first_multiple_input[1])

    result = superDigit(n, k)

    fptr.write(str(result) + '\n')

    fptr.close()
