#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'truckTour' function below.
#
# The function is expected to return an INTEGER.
# The function accepts 2D_INTEGER_ARRAY petrolpumps as parameter.
#

# =========== my code ==========

def truckTour(petrolpumps):
    # Write your code here
    tank = 0
    start_index = 0
    
    for i, pump in enumerate(petrolpumps):
        tank += pump[0]
        
        if tank - pump[1] > 0:
            tank -= pump[1]
        else:
            start_index = i + 1
            tank = 0
        
    return start_index

# ==============================

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input().strip())

    petrolpumps = []

    for _ in range(n):
        petrolpumps.append(list(map(int, input().rstrip().split())))

    result = truckTour(petrolpumps)

    fptr.write(str(result) + '\n')

    fptr.close()
